Error in .ddg.insert.error.message(error.msg) : 
  (converted from warning) No data node found for d
